### ISSUE TITLE
"ReferenceError: err is not defined"

### ISSUE THREAD

**Issue by d4h0** [joaoafrmartins/metalsmith-coffee#2]
Hi,

It seems on line 59 'err' should be '_error'.

I got the following error:

```

/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/lib/index.js:59
            return done(err);
                        ^
ReferenceError: err is not defined
  at Middleware.Coffee.Middleware.convert (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/lib/index.js:59:25)
  at /Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/lib/index.js:4:61
  at /Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/node_modules/async/lib/async.js:111:13
  at Array.forEach (native)
  at _each (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/node_modules/async/lib/async.js:32:24)
  at Object.async.each (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/node_modules/async/lib/async.js:110:9)
  at Middleware.Coffee.Middleware.plugin (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-coffee/lib/index.js:71:24)
  at Ware.<anonymous> (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:39:17)
  at next (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith/node_modules/ware/lib/index.js:75:20)
  at Ware.<anonymous> (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith-serve/lib/index.js:37:5)
  at Ware.<anonymous> (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:39:17)
  at Object.next [as _onImmediate] (/Users/dah/Projects/sites/1x1finanzierung.de/node_modules/metalsmith/node_modules/ware/lib/index.js:75:20)
  at processImmediate [as _immediateCallback] (timers.js:336:15)
```

Best regards,
Daniel

**Comment by jpetroff** [comment]
There was a typo catch then ... instead of catch err then ... 
Sent pull request.
